config/routes.rb
Hippo::Application.routes.draw do

  resources :users
  get "users/:id/orders" => "users#orders", as: :user_orders
  post "users/:id/ship/:op_id" => "users#ship", as: :ship_order
  get "users/:id/pending" => "users#pending", as: :pending
  get "users/:id/completed" => "users#completed", as: :completed

  resources :products do
    resources :category_products
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, except: [:new, :create, :index]

  get "/categories", to: "categories#index"
  get "/categories/:id", to: "categories#show", as: :category
  get "/products/:product_id/categories/new",
      to: "categories#new",
      as: :new_category
  post "/products/:product_id/categories/new",
       to: "categories#create", as: :create_category
  get "/sign-up"  => "users#new", as: :sign_up
  post "/sign-up" => "users#create", as: :create_user

  get "/sign-in"  => "sessions#new", as: :sign_in
  post "/sign-in" => "sessions#create", as: :signing_in
  get "/sign-out" => "sessions#destroy", as: :sign_out
  post "/orders/:id/add_product/:product_id",
       to: "orders#add_product",
       as: :add_product
  get "orders/:id", to: "orders#show", as: :order # cart
  delete '/orders/:id/remove_product/:product_id',
         to: "orders#remove_product",
         as: :remove_product
  patch '/orders/:id/update_quantity/:product_id',
        to: "orders#update_quantity",
        as: :update_quantity
  # get 'orders/shipping', to: 'orders#shipping', as: :shipping
  get "/search"         => "search#show"
  get "/shipping", to: "orders#shipping", as: :shipping
  post "/checkout"       => "orders#checkout", as: :checkout
  post "/purchase_info" => "orders#start_purchase", as: :start_purchase
  post "/purchase_info" => "orders#complete_purchase", as: :complete_purchase
  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :email, :password, :password_confirmation

  has_secure_password
  validates_presence_of :email, :on => :create
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :products
  has_many :orders
  has_many :reviews

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :edit, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      # attaches current order to newly created user
      current_order.update(user_id: @user.id)
      redirect_to root_path, notice: "You are now a hippo!"
    else
      render :new, notice: "There was a problem saving this user! :("
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "Your profile was successfully
                                                updated!"
    else
      render :edit, notice: "There was a problem updating your profile :("
    end
  end

  def edit
  end

  def destroy
  end

  def index
    @users = User.all
  end

  def show
    @products = @user.products
    @totals = find_total(@products)
    @paid = @products.map do |product|
      product.order_products.where.not(status: 'pending')
    end
    @bought =  @paid.map do |a|
      a.map { |op| op.quantity }
    end
    # returns array of total quantity bought per product
    @total_bought = @bought.map { |x| x.inject(:+) }
  end

  def search
    @users = User.where name: params[:name]
    render :index
  end

  def orders
    if params[:id].to_i != session[:user_id].to_i
      flash[:notice] = "You are not authorized to view this page!"
      redirect_to user_path(params[:id])
    else
      @user = User.find(params[:id])
      @products = @user.products
      @paid = @products.map do |product|
        product.order_products.where(status: "paid")
      end
    end
  end

  def pending
    if params[:id].to_i != session[:user_id].to_i
      flash[:notice] = "You are not authorized to view this page!"
      redirect_to user_path(params[:id])
    else
      @user = User.find(params[:id])
      @products = @user.products
      @pending = @products.map do |product|
        product.order_products.where(status: "pending")
      end
    end
  end

  def completed
    if params[:id].to_i != session[:user_id].to_i
      flash[:notice] = "You are not authorized to view this page!"
      redirect_to user_path(params[:id])
    else
      @user = User.find(params[:id])
      @products = @user.products
      @completed = @products.map do |product|
        product.order_products.where(status: "shipped")
      end
    end
  end

  def ship
    @op = OrderProduct.find(params[:op_id])
    @op.update(status: "shipped")
    redirect_to user_orders_path(session[:user_id], Order.find(@op.order_id))
    # update order to shipped
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def find_total(products)
    create_quantity = products.map do |product|
      product.order_products.map do |item|
        item.quantity if item.status == "pending"
      end
    end
    total = create_quantity.map do |qa|
      qa.compact.inject(:+)
    end
    total
  end

  def user_params
    params.require(:user).permit(
                                :name,
                                :email,
                                :seller_address,
                                :seller_address2,
                                :seller_city,
                                :seller_state,
                                :seller_zipcode,
                                :password,
                                :password_confirmation
                                )
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/completed.html.erb
 <h1>Completed orders</h1><hr>
  <div>
    <ol>
      <% @revenue = [] %>
      <% @completed.each do |array|%>
        <% if array != [] %>
          <% array.each do |op| %>
            <li>
              <% @product = Product.find(op.product_id) %>
                Product:<%= link_to "#{@product.name.capitalize}", product_path(@product) %><br>
                Quantity:<%= op.quantity %><br>
                Completed: <%= op.updated_at.utc.getlocal.strftime('%b %d, %Y at %l:%M %P') %><br>
                <% @subtotal = @product.price * op.quantity %>
                Total revenue: <%= number_to_currency @subtotal %>
                <% @revenue << @subtotal %>
              <hr>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ol>

  <h2>Total Revenue: <%= number_to_currency(@revenue.reduce(:+)) %></h2>

  </div>

app/views/users/edit.html.erb
<h1> Edit my profile </h1>
<%= form_for @user, url: user_path(@user.id), method: :patch do |f| %>
  <% if @user.errors.any? %>
  <div class= "error_messages">
    <h2> Form is invalid </h2>
    <ul>
      <% for message in @user.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Username" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "Please enter your email:" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Reset password:" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Re-enter password"%>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class= "actions"><%=f.submit %></div>


<% end %>

app/views/users/index.html.erb
<h1>Hippos</h1>
<ol>
<% @users.each do |user| %>
  <li> <%= user.email %></li>
  
<% end %>

</ol>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<h1>Become a Hippo!</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class= "error_messages">
    <h2> Form is invalid </h2>
    <ul>
      <% for message in @user.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Username" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "Please enter your email:" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address, "Please enter your address:" %>
    <%= f.text_field :seller_address %>
  </div>
  <div class="field">
    <%= f.label :address2, "Please enter suite or apartment numbers:" %>
    <%= f.text_field :seller_address2 %>
  </div>
    <div class="field">
    <%= f.label :city, "Please enter your city:" %>
    <%= f.text_field :seller_city %>
  </div>
    <div class="field">
    <%= f.label :state, "Please enter your state:" %>
    <%= f.text_field :seller_state %>
  </div>
    <div class="field">
    <%= f.label :zipcode, "Please enter your zipcode:" %>
    <%= f.text_field :seller_zipcode %>
  </div>
    <div class="field">
    <%#= f.label :country, "Please enter your country:" %>
    <%#= f.text_field :seller_country %>
  </div>
  <div class="field">
    <%= f.label :password, "Create password:" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Re-enter password"%>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class= "actions"><%= f.submit %></div>


<% end %>
  
  

app/views/users/orders.html.erb
<%#= @paid.inspect%>
<% if @paid.uniq == [] %>
  <h4>You have no orders to fulfill</h4>
<% else %>
  <h1>Paid orders</h1><hr>
  <div>
    <ol>
      <% @paid.each do |array|%>
        <% if array != [] %>
          <li>
            <% array.each do |op| %>
              Product:<%= Product.find(op.product_id).name %><br>
              Quantity:<%= op.quantity %><br>
              <% info = Order.find(op.order_id).purchase_info %><br>
              Ship to: 
              <div class= "shipping_address">
                <%= info.first_name %>
                <%= info.first_name %>
                <%= info.last_name %><br>
                <%= info.address %>
                <%= info.address2 if info.address2%><br>
                <%= info.city %>
                <%= info.state %>
                <%= info.zip_code %>
              </div><br>
              <div class="cc_info">
                Payment info:<br>
                CC: <%= info.credit_card_number.to_s.slice(-4,4) %><br>
                CVV: <%= info.cvv %><br>
                Expiration: <%= info.expiration_date %>
              </div>
                <%= button_to "Ship!", ship_order_path(params[:id], op.id) %>
              <hr>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ol>
  <% end %>

app/views/users/pending.html.erb
 <h1>Pending orders</h1><hr>
  <div>
    <ol>
      <% @pending.each do |array|%>
        <% if array != [] %>
          <% array.each do |op| %>
            <li>
              <% @product = Product.find(op.product_id) %>
              <% @order = Order.find(op.order_id) %>
                Product:<%= link_to "#{@product.name.capitalize}", product_path(@product) %><br>
                Quantity:<%= op.quantity %><br>
                Buyer: 
                <% if @order.user_id == nil %>
                Guest
                <% else %>
                <%= User.find(@order.user_id).name %><br>
                <% end %>
                Placed: <%= op.created_at.utc.getlocal.strftime('%b %d, %Y at %l:%M %P') %><br>
                <% @subtotal = @product.price * op.quantity %>
                Total revenue: <%= number_to_currency(@subtotal) %>
              <hr>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ol>
    

  </div>

app/views/users/show.html.erb
<h1><%= @user.name.upcase %></h1>

<% if session[:user_id] == @user.id %> 

  <ul id="userinfo">
    <li> USER NAME: <%= @user.name %> </li> 
    <li> USER EMAIL: <%= @user.email %></li>
  </ul>
    <hr>
  <!-- <h3>ORDERS TO FULFILL:</h3> -->

   <h3>ORDER FULFILLMENT:</h3>
    <ul>
      <li><%=link_to "Paid - Needs to be shipped!", user_orders_path(params[:id]) %></li>
     
      <li><%=link_to "Pending", pending_path(params[:id]) %></li>
      <li><%=link_to "Completed", completed_path(params[:id]) %></li>
    </ul>
    <hr>
  <h3>PRODUCTS:</h3>
  <%=button_to "List a new product", new_product_path, method: :get %><br>
    <table>
      <thead>
        <tr>
          <th> Product name</th>
          <th> Inventory </th>
          <th> Items ordered </th>
          <th> Total sold </th>
        </tr>
      </thead>
      <tbody>
        <% @user.products.each do |product|%>
          <tr>
            <td id="product_name"><%= link_to "#{product.name}", product_path(product.id)%></td>
            <td id="inventory"><%= product.inventory %></td>
            <% if product.retired == true %>
              <td id="items_ordered"> This product has been retired </td>
              <td id="ship"></td>
            <% else %>
            <td id="items_ordered"><%= @totals.fetch(@user.products.index(product)) %></td> 
            <td id="ship"></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h3>ORDER HISTORY:</h3>
      <table>
        <thead>
          <tr>
            <th> Order </th>
            <th> Status </th>
            <th> Items in Order </th>
            <th> Created on </th>
            <th> Last Updated </th>
          </tr>
        </thead>
        <tbody>
          <% @user.orders.reverse.each do |order|%>
           <tr> 
            <% if order == current_order %>
              <td><%= link_to "Current order", order_path(current_order) %></td>
              <!-- the next elsif block will be condensed into the current order -->
            <% elsif order.status == "pending" %> 
              <td><%= link_to "Order \# #{order.id}", order_path(order) %></td>
              <!-- end the part that will be condesned -->
            <% elsif order.status != "pending" %>
              <td><%= link_to "Order \# #{order.id}", order_path(order) %></td>
            <% end %>
            <td><%= order.status %></td>
            <td><%= order.products.count %></td>
            <td><%= order.created_at.strftime('%b %d, %Y at %l:%M %P') %></td>
            <td><%= order.updated_at.strftime('%b %d, %Y at %l:%M %P') %></td> 
            <!-- #maybe change order of table elements? if shipped, show completion date -->
           </tr>
          <% end %>
        </tbody>
      </table>
<br>    


<% else %>

  <h3>Products sold by <%=@user.name%>:</h3>

  <%= render 'products/index' %>

<% end %>