config/routes.rb
Hippo::Application.routes.draw do

  resources :users
  get "users/:id/orders" => "users#orders", as: :user_orders
  post "users/:id/ship/:op_id" => "users#ship", as: :ship_order
  get "users/:id/pending" => "users#pending", as: :pending
  get "users/:id/completed" => "users#completed", as: :completed

  resources :products do
    resources :category_products
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, except: [:new, :create, :index]

  get "/categories", to: "categories#index"
  get "/categories/:id", to: "categories#show", as: :category
  get "/products/:product_id/categories/new",
      to: "categories#new",
      as: :new_category
  post "/products/:product_id/categories/new",
       to: "categories#create", as: :create_category
  get "/sign-up"  => "users#new", as: :sign_up
  post "/sign-up" => "users#create", as: :create_user

  get "/sign-in"  => "sessions#new", as: :sign_in
  post "/sign-in" => "sessions#create", as: :signing_in
  get "/sign-out" => "sessions#destroy", as: :sign_out
  post "/orders/:id/add_product/:product_id",
       to: "orders#add_product",
       as: :add_product
  get "orders/:id", to: "orders#show", as: :order # cart
  delete '/orders/:id/remove_product/:product_id',
         to: "orders#remove_product",
         as: :remove_product
  patch '/orders/:id/update_quantity/:product_id',
        to: "orders#update_quantity",
        as: :update_quantity
  # get 'orders/shipping', to: 'orders#shipping', as: :shipping
  get "/search"         => "search#show"
  get "/shipping", to: "orders#shipping", as: :shipping
  post "/checkout"       => "orders#checkout", as: :checkout
  post "/purchase_info" => "orders#start_purchase", as: :start_purchase
  post "/purchase_info" => "orders#complete_purchase", as: :complete_purchase
  root 'welcome#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :products, through: :order_products
  has_many :order_products
  has_one :purchase_info


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, except: [:new, :create, :show]
  # don't want to show only current order
  before_action :set_products, only: [:add_product,
                                      :update_quantity,
                                      :checkout]
  before_action :check_order, only: [:add_product]
  before_action :totals, only: [:update_quantity, :checkout] #:update_quantity, 

  def new
    @order = Order.new
  end

  def create
  end

  def shipping
    @purchase_info = PurchaseInfo.new
  end

  def edit
  end

  def update
  end

  def show
    if Order.find_by(id: params[:id]).nil?
      flash[:notice] = "This order does not exist."
      redirect_to root_path
    else
      @order = Order.find(params[:id])
      @products = @order.products
      # @stati = @order.order_products.map { |op| op.status }
      # unless (@stati.include? "pending") || (@stati.include? "paid")
      #   @order.update(status:"complete")
      # end
      # commenting out above now does not update the orders status to
      # complete once all OPs are shipped
      # put a guard here to remove products from cart if you own it
      # (happens if bought as a guest then signed in)
      unless @products == nil?
        totals
      end
    end
  end

  def add_product
    if check_order
      flash[:notice] = "You already have this product in your cart!"
      redirect_to order_path(current_order)
    else
      @product = Product.find(params[:product_id])
      if @product.inventory == 0
        flash[:notice] = "This product is out of stock. Check back soon!"
        redirect_to root_path
      else
        @orderproduct = OrderProduct.new(
        order_id: current_order.id,
        product_id: params[:product_id],
        quantity: params[:quantity],
        status: "pending")
        if @orderproduct.save
          redirect_to order_path(current_order) # changes url
        else
          flash.now[:notice] = "There was a problem adding this item
                                to the cart."
          # render doesn't show notice b/c generates page first
          render :show
        end
      end
    end
  end

  def remove_product
    @orderproduct = OrderProduct.find_by(order_id: current_order.id,
                                         product_id: params[:product_id])
    @orderproduct.destroy
    redirect_to order_path(current_order)
    # why doesn't need to be current_order.id?
  end

  def update_quantity
    @orderproduct = OrderProduct.find_by(order_id: current_order.id,
                                         product_id: params[:product_id])
    if @orderproduct.update(quantity: params[:quantity])
      redirect_to order_path(current_order)
    else
      flash.now[:notice] = "There was problem updating your order."
      render :show
    end
  end

  def checkout
    @purchase_info = PurchaseInfo.new(params.require(:purchase_info).permit(:address,
                                    :address2,
                                    :city,
                                    :state,
                                    :zip_code))
    if @purchase_info.save
      @order = current_order
      @products = current_order.products

      if @products
        @products.each do |product|
          @shippings = []
          @shippings << HTTParty.post("http://localhost:4000/rates.json",{:body => {:origin => {:country => 'US', :state => "#{product.user.seller_state}", :city => "#{product.user.seller_city}", :zip => "#{product.user.seller_zipcode}"}, :destination => {:country => 'US', :state => "#{params[:purchase_info][:state]}", :city => "#{params[:purchase_info][:city]}", :zip => "#{params[:purchase_info][:zip_code]}"}, :package => {:weight => "#{product.weight}", :height => "#{product.height}", :depth => "#{product.depth}", :length => "#{product.length}"}}})
        end
      end

      @purchase_info = PurchaseInfo.new
      current_order.products.each do |product|
        if product.inventory == 0 #make check inv method?
          flash[:notice] = "We are currently out of stock.
                            Please modify your order."
          redirect_to order_path(current_order)
        elsif OrderProduct.find_by(product_id: product.id,
                                   order_id: current_order.id
                                   ).quantity > product.inventory
          flash[:notice] = "We have #{product.inventory} of those in stock.
                            Please modify your order."
          redirect_to order_path(current_order)
        else
          # product.update(
          #   inventory: product.inventory - OrderProduct.find_by(
          #     product_id: product.id,
          #     order_id: current_order.id
          #   ).quantity)
        end
      end
    else

      render :shipping
    end
  end

  def start_purchase
    @purchase_info = PurchaseInfo.new(purchase_params)
    @purchase_info[:order_id] = current_order.id
  end

  def complete_purchase
    # @purchase_info = PurchaseInfo.new(purchase_params)
    # @purchase_info[:order_id] = current_order.id
    current_order.update(status: "paid")
    # session[:order_id] = nil # reset current order
    current_order.order_products.each do |op|
      op.update(status: "paid")
    end
    if @purchase_info.save
      flash[:notice] = "Thank you for your purchase!
                        Your order should be shipped
                        within 7-10 business days!"
      current_order = Order.new
      # This needs to archive paid order and open a new one
      redirect_to root_path
    else
      flash[:notice] = "There was an error processing your order."
      render :checkout
    end
  end

  private

  def check_user
    @orderu = current_order.user_id
    @orderu == session[:user_id]
  end

  # Checks if product already exists in an order
  def check_order
    @product = Product.find(params[:product_id])
    OrderProduct.find_by(product_id: @product.id,
                         order_id: current_order.id).present?
  end

  # Checks if any products in order are owned by the buyer
  # def check_products
  #   @order = Order.find(params[:id])
  #   @user = User.find(@order.user_id)
  #   @products = @order.products.each do |product|
  #     if product.user_id == @user.id
  #       flash[:notice] = "#{product} has been removed from your order!"
  #       OrderProduct.find_by(product_id:product.id,
  #       order_id: @order.id).destroy
  #     end
  #   end
  # end

  def set_order
    @order = current_order
  end

  def set_products
    @products = current_order.products
  end

  def totals
    @items = current_order.order_products.map { |x| x.quantity }
    @item_total =  @items.inject(:+)
    @subtotals = @products.map do |product|
      product.price * OrderProduct.find_by(
                                          product_id: product.id,
                                          order_id: @order.id
                                          ).quantity
    end
    @total = @subtotals.reduce(:+)
  end

  def purchase_params
    params.require(:purchase_info).permit(
    :first_name, :last_name, :billing_first, :billing_last,
    :credit_card_number, :expiration_date, :cvv,
    :billing_address, :billing_address2, :billing_city, :billing_state,
    :billing_zip_code
    )
  end

  helper_method :check_user
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/checkout.html.erb
<script>
$( document ).ready(function() {
  $("input[type=submit]:last").attr("disabled", "disabled");

  $("input[name=shipping_price]:radio").change(function() {
    $("#shipping_total").text($("input[name=shipping_price]:checked").val());
    $("#total_price").text(parseFloat($("#product_total").text().replace("$",""))+parseFloat($("#shipping_total").text().replace("$","")));
    $("input[type=submit]:last").removeAttr("disabled");
  });
});
</script>

<h3>Shipping Information</h3>

<% if check_user %>
  <div class= "ordershow">
    <% if @products == [] %>
      <h3> There are no products in this order.</h3>
    <% else %>
    <!-- maybe refactor to case when syntax? -->
      <% if @order.status == "pending" %>
        <h3>This order has not been checked out!</h3>
      <% elsif @order.status == "paid" %>
        <h3>This order is being processed!</h3>
      <% elsif @order.status == "complete" %>
        <h3> This order has been completed! </h3>
      <% end %>
    <!-- end status message -->

    <table>
      <thead>
        <tr>
          <th> Name      </th>
          <th> Quantity  </th>
          <th> Price     </th>
          <th> Subtotal  </th>
          <!-- only want this column if order has been paid for -->
          <% unless @order.status == "pending" %>
            <th> Status    </th>
          <% end %>
          <% if @order.status == "pending" %>
            <th> Edit quantity  </th>
            <th> Remove         </th>
          <% end %>
        </tr>
      </thead>
      <tbody> 
        <% @products.each do |product| %>
          <% if product.user_id != session[:user_id] %>
          <tr>
            <td id= "item name"><%= link_to "#{product.name.capitalize}", product_path(product) %></td>
            <td id="quantity"><%= OrderProduct.find_by(product_id: product.id, order_id: @order.id).quantity %></td>
            <td id="price"><%= number_to_currency(product.price) %></td>
            <td id= "subtotal"><%= number_to_currency @subtotals[@products.index(product)]%></td>
            <!-- only shows status of products if order has been checked out -->
            <% unless @order.status == "pending" %>
              <td id= "status"><%= @order.order_products.find_by(product_id:product.id, order_id:@order.id).status %></td>
            <% end %>
            <!-- Can edit/remove if order still open --> 
            <% if @order.status == "pending" %>
              <td id= "edit_quantity">
                <%= form_tag(update_quantity_path(@order.id, product.id), method: "patch") do %>
                  <%= number_field_tag(:quantity, params[:quantity], in: 1..product.inventory, class: "number_field") %>
                  <%= submit_tag "Update!" %>
                <% end %>
              </td>
              <td id= "remove"><%= button_to "Remove", remove_product_path(current_order.id, product.id), method: :delete %>
              </td>
            <% end %>
          </tr>
          <%# else %>
          <%# OrderProduct.find_by(product_id: product.id, order_id: @order.id).destroy %>
           <!--  You cannot purchase  --><%#=product.name %> 
          <% end %>
        <% end %> <!-- end iteration -->
        
        <tr>
          <td>TOTAL:</td>
          <td> 
            <% items = current_order.order_products.map {|x| x.quantity} %>
            <%= items.inject(:+) %>
          </td>
          <td></td>
          <td><%= number_to_currency(@total)%></td>
          <% if @order.status == "pending" %>
            <td></td>
            <td></td>
          <% end %>
          <% unless @order.status == "pending" %>
            <td></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  <br><hr>

<!--     <div class="navigation_links">
      <! Maybe just go to checkout with a notice "You have no items in your cart? -->
     <!--  <div class="checkout_button">
        <#% if @order.status == "pending" %>  
          <#%= button_to "Proceed to checkout", checkout_path, method: :get %><br>
        <#% end %>
      </div>
    <#% end %> -->

    <% end %>

      <%= link_to "Back to browsing", root_path %><br><br>
      <% if current_user %>
        <%= link_to "Back to profile", user_path(current_user.id) %>
      <% end %>
    </div> <!-- ends ordershow -->
  <hr>

<% else %>
  <h3>You are not authorized to view this page!</h3>  
<% end %>

<!-- Shipping Call -->
<%= form_for @purchase_info, url: {action: "start_purchase" } do |f| %>
<hr>
<h3>Shipping Options:</h3>
  <table>
    <thead>
      <tr>
        <th>Provider</th>
        <th>Est. Delivery Date</th>
        <th>Price</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% @shippings.each do |ship| %>
      <% ship.each do |company| %>
      <% company[1..2].each do |offering| %>
      <tr>
       <td style= "text-align: left"> <%= offering["service"] %></td>
       <td> <%= offering["delivery_range"] %> </td>
       <td> <%= offering["price"]/100.00 %> </td>
       <td> <input type="radio" name="shipping_price" value="<%= offering["price"]/100.00 %>"></td>
      </tr>
      <% end %>
      <% end %>
      <% end %>
    </tbody>
  </table>

<!-- strftime("%b %e, %Y") -->
<!-- Time.now.strftime("%b %e, %Y") -->


<!-- Total (Products + Shipping) -->

<br><hr>
<h3>Order Total:</h3>
  <table>
    <thead>
      <tr>
        <th>Product Subtotal</th>
        <th>Shipping</th>
        <th>TOTAL</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><p id = "product_total"><%= number_to_currency(@total)%></p></td>
        <td><p id ="shipping_total"></p></td>
        <td><p id ="total_price"></p></td>
      </tr>
    </tbody>
  </table>


<!-- Checkout Forms -->


<br><hr>
  <h3>Billing Information:</h3>

  <% if @purchase_info.errors.any? %>
  <div class= "error_messages">
    <h2> Problem in Form </h2>
    <ul>
      <% @purchase_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    <%= f.label :billing_first %>:
    <%= f.text_field :billing_first %>
  </div>
  <div class="field">
    <%= f.label :billing_last %>:
    <%= f.text_field :billing_last %>
  </div>
  <div class="field">
    <%= f.label :billing_address %>:
    <%= f.text_field :billing_address %>
  </div>
  <div class="field">
    <%= f.label :billing_address2 %>:
    <%= f.text_field :billing_address2 %>
  </div>
  <div class="field">
    <%= f.label :billing_city %>:
    <%= f.text_field :billing_city %>
  </div>
  <div class="field">
    <%= f.label :billing_state %>:
    <%= f.text_field :billing_state %>
  </div>
  <div class="field">
    <%= f.label :billing_zip_code %>:
    <%= f.number_field :billing_zip_code %>
  </div>
  <div class="field">
    <%= f.label :credit_card_number %>:
    <%= f.text_field :credit_card_number %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %>:
    <%= f.text_field :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :cvv %>:
    <%= f.text_field :cvv %>
  </div>
  <br>
  <%= f.submit "Submit Order", url: complete_purchase_path %> 
<% end %>

<hr>
<%= link_to "Edit your order", order_path(current_order.id) %>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
params <%=params.inspect%>

<h1>Buy things!</h1>

  <%= form_for @order, url: "/user/#{@user.id}/add_product/#{.id}" do |p| %>
     <%= p.label :notes %><br />
     <%= p.text_area :notes %>

     <%= submit_tag("Update") %>
  <%end%>


<% end %>
  
  

app/views/orders/shipping.html.erb
<h3>Shipping Address:</h3>
<!-- address action neeeds to match billing route;  -->

  <%= form_for @purchase_info, url: {action: "checkout" } do |f| %>
  <% if @purchase_info.errors.any? %>
  <div class= "error_messages">
    <h2> Problem in Form </h2>
    <ul>
      <% @purchase_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>:
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>:
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %>:
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %>:
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city, "City" %>:
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state, "State" %>:
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code, "Zip Code" %>:
    <%= f.number_field :zip_code %>
  </div>

    <%= f.submit "Proceed to Shipping Options" %>
<% end %>

<hr>
<%= link_to "Edit your order", order_path(current_order.id) %>

app/views/orders/show.html.erb
<%=flash.notice %>

<!-- Ensures only buyer can see full order -->
<% if check_user %>
  <div class= "ordershow">
    <% if @products == [] %>
      <h3> There are no products in this order.</h3>
    <% else %>
    <!-- maybe refactor to case when syntax? -->
      <% if @order.status == "pending" %>
        <h3>This order has not been checked out!</h3>
      <% elsif @order.status == "paid" %>
        <h3>This order is being processed!</h3>
      <% elsif @order.status == "complete" %>
        <h3> This order has been completed! </h3>
      <% end %>
    <!-- end status message -->

    <table>
      <thead>
        <tr>
          <th> Name      </th>
          <th> Quantity  </th>
          <th> Price     </th>
          <th> Subtotal  </th>
          <!-- only want this column if order has been paid for -->
          <% unless @order.status == "pending" %>
            <th> Status    </th>
          <% end %>
          <% if @order.status == "pending" %>
            <th> Edit quantity  </th>
            <th> Remove         </th>
          <% end %>
        </tr>
      </thead>
      <tbody> 
        <% @products.each do |product| %>
          <% if product.user_id != session[:user_id] %>
          <tr>
            <td id= "item name"><%= link_to "#{product.name.capitalize}", product_path(product) %></td>
            <td id="quantity"><%= OrderProduct.find_by(product_id: product.id, order_id: @order.id).quantity %></td>
            <td id="price"><%= number_to_currency(product.price) %></td>
            <td id= "subtotal"><%= number_to_currency @subtotals[@products.index(product)]%></td>
            <!-- only shows status of products if order has been checked out -->
            <% unless @order.status == "pending" %>
              <td id= "status"><%= @order.order_products.find_by(product_id:product.id, order_id:@order.id).status %></td>
            <% end %>
            <!-- Can edit/remove if order still open --> 
            <% if @order.status == "pending" %>
              <td id= "edit_quantity">
                <%= form_tag(update_quantity_path(@order.id, product.id), method: "patch") do %>
                  <%= number_field_tag(:quantity, params[:quantity], in: 1..product.inventory, class: "number_field") %>
                  <%= submit_tag "Update!" %>
                <% end %>
              </td>
              <td id= "remove"><%= button_to "Remove", remove_product_path(current_order.id, product.id), method: :delete %>
              </td>
            <% end %>
          </tr>
          <% else %>
          <% OrderProduct.find_by(product_id: product.id, order_id: @order.id).destroy %>
            You cannot purchase <%=product.name %> 
          <% end %>
        <% end %> <!-- end iteration -->
        
        <tr>
          <td>TOTAL:</td>
          <td> 
            <% items = current_order.order_products.map {|x| x.quantity} %>
            <%= items.inject(:+) %>
          </td>
          <td></td>
          <td><%= number_to_currency(@total) %></td>
          <% if @order.status == "pending" %>
            <td></td>
            <td></td>
          <% end %>
          <% unless @order.status == "pending" %>
            <td></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  <br><hr>
    <div class="navigation_links">
      <!-- Maybe just go to checkout with a notice "You have no items in your cart? -->
      <div class="checkout_button">
        <% if @order.status == "pending" %>  
          <%= button_to "Proceed to shipping options", shipping_path, method: :get %><br>
        <% end %>
      </div>
    <% end %>

      <%= link_to "Back to browsing", root_path %><br><br>
      <% if current_user %>
        <%= link_to "Back to profile", user_path(current_user.id) %>
      <% end %>
    </div> <!-- ends ordershow -->
  <hr>

<% else %>
  <h3>You are not authorized to view this page!</h3>  
<% end %>

app/views/orders/start_purchase.html.erb
Thanks for your order!

<%= current_order.inspect %>
<hr>

<div>You have successfully paid!
  <br>

  Your order will be shipped to:<br><br>
  <div>
    <% if current_user %>
    <%= current_user.name %><br>
    <% end %>
  <%=params[:address1]%>
  <%=params[:address2]%><br>
  <%=params[:city]%>, <%=params[:state]%><br>
  <%=params[:zipcode]%>
  </div>
  <br>
</div>
  Your order should arrive in 7-10 business days.<br><br>

<%= link_to "Keep shopping!", root_path %>

app/views/orders/submit.html.erb
<%= current_order.inspect %>
<hr>

<div>You have successfully paid!
  <br>

  Your order will be shipped to:<br><br>
  <div>
    <% if current_user %>
    <%= current_user.name %><br>
    <% end %>
  <%=params[:address1]%>
  <%=params[:address2]%><br>
  <%=params[:city]%>, <%=params[:state]%><br>
  <%=params[:zipcode]%>
  </div>
  <br>
</div>
  Your order should arrive in 7-10 business days.<br><br>

<%= link_to "Keep shopping!", root_path %>