config/routes.rb
Hippo::Application.routes.draw do

  resources :users
  get "users/:id/orders" => "users#orders", as: :user_orders
  post "users/:id/ship/:op_id" => "users#ship", as: :ship_order
  get "users/:id/pending" => "users#pending", as: :pending
  get "users/:id/completed" => "users#completed", as: :completed

  resources :products do
    resources :category_products
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, except: [:new, :create, :index]

  get "/categories", to: "categories#index"
  get "/categories/:id", to: "categories#show", as: :category
  get "/products/:product_id/categories/new",
      to: "categories#new",
      as: :new_category
  post "/products/:product_id/categories/new",
       to: "categories#create", as: :create_category
  get "/sign-up"  => "users#new", as: :sign_up
  post "/sign-up" => "users#create", as: :create_user

  get "/sign-in"  => "sessions#new", as: :sign_in
  post "/sign-in" => "sessions#create", as: :signing_in
  get "/sign-out" => "sessions#destroy", as: :sign_out
  post "/orders/:id/add_product/:product_id",
       to: "orders#add_product",
       as: :add_product
  get "orders/:id", to: "orders#show", as: :order # cart
  delete '/orders/:id/remove_product/:product_id',
         to: "orders#remove_product",
         as: :remove_product
  patch '/orders/:id/update_quantity/:product_id',
        to: "orders#update_quantity",
        as: :update_quantity
  # get 'orders/shipping', to: 'orders#shipping', as: :shipping
  get "/search"         => "search#show"
  get "/shipping", to: "orders#shipping", as: :shipping
  post "/checkout"       => "orders#checkout", as: :checkout
  post "/purchase_info" => "orders#start_purchase", as: :start_purchase
  post "/purchase_info" => "orders#complete_purchase", as: :complete_purchase
  root 'welcome#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  has_many :products, through: :category_products
  has_many :category_products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    require_login
    @category = Category.new
    # @product = Product.find(params[:product_id])
  end

  def create
    @product = Product.find(params[:product_id])
    @category = Category.new(category_params)
    if @category.save
      CategoryProduct.create(
                            product_id: params[:product_id],
                            category_id: @category.id
                            )
      redirect_to edit_product_path(params[:product_id])
    else
      flash[:notice] = "This category already exists!"
      redirect_to new_category_path(@product)
    end
  end

  def index
    @categories = Category.all.map do |c|
      [c, c.products.count]
    end
    @top_categories = @categories.sort_by { |x| x[1] }.reverse
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_new_cat.html.erb
<h1>Create a new Category!</h1>
<%= form_for @category, url: create_category_path(Product.find(params[:product_id])) do |f| %>
  <% if @category.errors.any? %>
  <div class= "error_messages">
    <h2> Form is invalid </h2>
    <ul>
      <% for message in @category.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Category:" %>
    <%= f.text_field :name %><br><br>
  </div>

  <div class= "actions"><%=f.submit %></div>


<% end %>

app/views/categories/_sidebar_index.html.erb
<ul class="categories">
<% @top_categories.take(40).each do |category| %>
    <li>
    <%=link_to "#{category.first.name.capitalize}", category_path(category.first.id) %>
    </li>
    <br>
<% end %> 
</ul class= "categories">

app/views/categories/index.html.erb
<ul class="categories">
<% @top_categories.each do |category| %>
    <li>
    <%=link_to "#{category.first.name.upcase}", category_path(category.first.id) %>
    <%= category[1]%>
    </li>
<% end %> 
</ul class= "categories">

app/views/categories/new.html.erb
<%=flash.notice %>
<hr>

<h1>Create a new Category!</h1>
<%= form_for @category, url: create_category_path(Product.find(params[:product_id])) do |f| %>
  <% if @category.errors.any? %>
  <div class= "error_messages">
    <h2> Form is invalid </h2>
    <ul>
      <% for message in @category.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Category:" %>
    <%= f.text_field :name %><br><br>
  </div>

  <div class= "actions"><%=f.submit %></div>


<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name.upcase %></h1>
<%= render 'products/index' %> 
<%= link_to "Back to Browse by Category", categories_path %>