config/routes.rb
Hippo::Application.routes.draw do

  resources :users
  get "users/:id/orders" => "users#orders", as: :user_orders
  post "users/:id/ship/:op_id" => "users#ship", as: :ship_order
  get "users/:id/pending" => "users#pending", as: :pending
  get "users/:id/completed" => "users#completed", as: :completed

  resources :products do
    resources :category_products
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, except: [:new, :create, :index]

  get "/categories", to: "categories#index"
  get "/categories/:id", to: "categories#show", as: :category
  get "/products/:product_id/categories/new",
      to: "categories#new",
      as: :new_category
  post "/products/:product_id/categories/new",
       to: "categories#create", as: :create_category
  get "/sign-up"  => "users#new", as: :sign_up
  post "/sign-up" => "users#create", as: :create_user

  get "/sign-in"  => "sessions#new", as: :sign_in
  post "/sign-in" => "sessions#create", as: :signing_in
  get "/sign-out" => "sessions#destroy", as: :sign_out
  post "/orders/:id/add_product/:product_id",
       to: "orders#add_product",
       as: :add_product
  get "orders/:id", to: "orders#show", as: :order # cart
  delete '/orders/:id/remove_product/:product_id',
         to: "orders#remove_product",
         as: :remove_product
  patch '/orders/:id/update_quantity/:product_id',
        to: "orders#update_quantity",
        as: :update_quantity
  # get 'orders/shipping', to: 'orders#shipping', as: :shipping
  get "/search"         => "search#show"
  get "/shipping", to: "orders#shipping", as: :shipping
  post "/checkout"       => "orders#checkout", as: :checkout
  post "/purchase_info" => "orders#start_purchase", as: :start_purchase
  post "/purchase_info" => "orders#complete_purchase", as: :complete_purchase
  root 'welcome#index'
end

app/models/product.rb
class Product < ActiveRecord::Base

   validates :name, presence: true, uniqueness: { case_sensitive: false }
   validates :price, presence: true, numericality: { greater_than: 0 }
   validates :user_id, presence: true
   validates :description, presence: true #has photo...CarrierWave???
   validates :inventory, presence: true, numericality: { greater_than: -1 }

   belongs_to :user
   has_many :categories, -> { uniq }, through: :category_products
   has_many :category_products
   has_many :orders, through: :order_products
   has_many :order_products
   has_many :reviews

   mount_uploader :photo, DisplayUploader
   
end

app/controllers/products_controller.rb
# foobar
class ProductsController < ApplicationController
  before_action :set_product, except: [:new, :create]

  # def index
  #   @products = Product.all
  #   render partial: "index"
  # end

  def show  # compare w/users
    @users = User.all
  end

  def new
    if current_user
      @product = Product.new # (user_id: params[:user_id])
    else
      redirect_to sign_in_path, notice: "You must sign in to list a product!"
    end
  end

  def create
    @product = Product.new(product_params)
    # Following would be unnecessary if route was renamed RESTfully
    @product.user_id = current_user.id

    if @product.save
      msg = "You have successfully listed this product!"
      redirect_to @product, notice: msg
    else
      msg = "There was an error, try again."
      redirect_to new_product_path, notice: msg
    end
  end

  def edit
    if @product.user_id != session[:user_id]
      flash[:notice] = "You are not authorized to edit this product!"
      redirect_to "/products/#{@product.id}"
    else
      true
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def search_by_name
    @products = Product.where name: params[:product]
  end

  private

  def product_params
    params.require(:product).permit(:name,
                                    :price,
                                    :user_id,
                                    :inventory,
                                    :description,
                                    :photo,
                                    :retired,
                                    :length,
                                    :weight,
                                    :height,
                                    :depth)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_category_form.html.erb
<% unless Category.all == [] %> 
  <%= form_for @product, url: product_category_product_path(product_id: @product.id) do |f| %>  
    <p>Choose the categories that describe this product:</p>
    <div>
      <%= f.select(:category_products,
                 Category.all.collect { |p| [p.name, p.id] },
                 {:selected => CategoryProduct.where(:product_id => @product.id).map(&:category_id)},
                 {'name' => 'product[category][]', :multiple => true}) %>
    </div>
    <br>
    <div class= "actions">
      <%= f.submit "Update categories" %>
    </div>
  <% end %>
<% end %>

<br>
<div>Want to create a new category?
  <%= link_to "Create new Category", create_category_path(@product) %>
</div>

<br>

app/views/products/_base_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
  <div class= "error_messages">
    <h2> Form is invalid </h2>
    <ul>
      <% for message in @product.errors.full_messages %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price, "How much?" %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label(:retired) %>
    <%= f.check_box :retired %>
  </div>
  <div class="field">
    <%= f.label :inventory %>
    <%= f.number_field :inventory %>
  </div>
  <div class="field">
    <%= f.label :weight_in_oz %>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :depth %>
    <%= f.text_field :depth %>
  </div>
  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length %>
  </div>
  <div class="image">
    <%= f.label :photo, "Upload an image of your product!" %>
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %> <!-- what is this? -->
  </div>
  <div class= "actions"><%=f.submit %></div>
<% end %>

app/views/products/_edit_category_form.html.erb
<h3>Categories:</h3>
  <ul><% unless @product.categories == [] %> 
  <%= form_for @product do |f| %> 
    <% @product.categories.each do |c| %>
      <li><%= c.name %>
      <%= link_to 'Remove', product_category_product_path(product_id: @product.id, id: c.id), method: :delete, data: { confirm: 'Are you sure you want to remove this category?' } %>
    </li>
    <% end %>
  <% end %>
<% end %>

</ul>

app/views/products/_index.html.erb
<div class="productlist">  
  <% @products.each do |product| %>
    <!-- guard against users viewing own products (Do we really want this?) -->
    <% if product.user_id != session[:user_id] %> 
      <ul class="individualproduct">
        <!-- guard against viewing retired products -->
        <% unless product[:status] == "retired" %>
          <li id="productname"><li><%= link_to "#{product.name.capitalize}", product_path(product.id) %></li>
          <li><% if product.photo.present? %>
              <%= image_tag(product.photo_url(:thumb))  %>
                <% else %>
              <%= image_tag("hellohippo.png") %>
                <% end %>
          </li>
          <li><%= number_to_currency(product.price) %></li>
          <li id="cartbutton">
            <!-- Add to cart button. Ensures that user cannot add product if none in stock -->
            <% if product.inventory == 0 %>
              <p> Out of stock </p>
            <% else %>
              <%= form_tag(add_product_path(current_order.id, product.id), method: "post") do %>
                <%=  number_field_tag(:quantity, 1, in: 1..product.inventory) %>
                <%=  submit_tag "Add to Cart" %>
              <% end %>
            <% end %>
          </li>
          <!-- end button -->
        <% end %> 
        <!-- ends retired clause -->
      </ul>
    <% end %>
    <!-- ends guard against users viewing own products (Do we really want this?) -->
  <% end %>
</div>

  

app/views/products/edit.html.erb
<h1><%= @product.name.upcase %></h1>

<h1>Edit a product</h1>

<hr>
<%= @product.photo %>

<%= render 'base_form' %>
<hr>
<%= render 'edit_category_form' %>
<hr>
<%= render 'add_category_form' %>

app/views/products/index.html.erb
params <%=params.inspect%><br>
<hr>
NOTICE: <%=flash[:notice] %>


<!-- **The following div is temporary! ** List top categories here
   * put top_categories array in application controller (right now only in catoegory controller-also need in welcome controller) -->

<!-- <div class="sidebar">
  <#% Category.all.each do |category| %>
  <#%= link_to "#{category.name.upcase}", category_path(category) %>
  <#% end %>
</div> -->

<div>
  <ul>
    <% @products.each do |product| %>
      <% unless product[:status] == "retired" %>
        <li><%= link_to "#{product.name.capitalize}", product_path(product.id) %></li>
        <li><%= image_tag(src=@product.photo, size: '150x150') %></li>
        <li><%= number_to_currency(product.price) %></li>
        <li><%= product.inventory %></li>
        <li><%= product.description %></li> 
        <li>
          <% if session[:user_id] %>
            <% if product.user_id != current_user.id %>
            <%= form_tag(add_product_path(current_order.id, product.id), method: "post") do %>
                  <%=  number_field_tag(:quantity, 1, in: 1..product.inventory) %>
                  <%=  submit_tag "Add to Cart" %>
                <% end %>
            <% end %>
          <% end %>
        </li>

      <% end %>
    <%end %>      
  </ul>
</div>

app/views/products/new.html.erb
<h1>List a product</h1>

<%= render 'base_form' %>

app/views/products/show.html.erb
<div class= "productshow">

<h1 id="productshowname"><%= @product.name.capitalize %></h1>
  <div id="productphoto"><%= image_tag(@product.photo_url(:showpage)) if @product.photo%></div>
    <h3>Price:</h3><li><%= number_to_currency(@product.price) %></li>
    <h3>Description:</h3>
    Product Description:
    <li> <%= @product.description %></li>
    Product Dimensions:
    <li><%= @product.weight %> oz in weight</li>
    <li><%= @product.height %> inches high</li>
    <li><%= @product.depth %> inches deep</li>
    <li><%= @product.length %> inches long</li>

    <h3>Categories:</h3>
    <ul>
      <% unless @product.categories == [] %>
        <% @product.categories.each do |category|%>
           <li><%= link_to "#{category.name}", category_path(category.id) %></li>
        <% end %>
      <% else %>
        <p>There are no categories associated with this product.</p>
      <% end %>
    </ul>

    <!-- makes sure product can't be purchased by owner of the product -->
    <% if @product.user_id != session[:user_id] %>
       <% if @product.inventory == 0 %>
         <p> Out of stock -- Check back soon!</p>
       <% else %>
        <%= form_tag(add_product_path(current_order.id, @product.id), method: "post") do %>
          <%= number_field_tag(:quantity, 1, in: 1..@product.inventory) %>
          <%= submit_tag "Add to Cart" %>
        <% end %>
      <% end %>
    <% end %> 
    <hr>  
  
    <!--  starts reviews -->
    <h3>Reviews:</h3>
    <% unless @product.user_id == session[:user_id] %>
        <%= link_to "Add a review!", new_product_review_path(@product) %><br>
      <% end %> 
    <hr>
    <ul>
      <% if @product.reviews == [] %>
        <p>There are no reviews for this product.</p>
      <% else %>
        <% array = @product.reviews.map do |review| %>
          <%[review, review.created_at] %>
        <% end %>
        <% @reviews = array.sort_by { |x| x[1]}.reverse.take(3) %>
        <% @reviews.each do |review| %>
          <li>
          <h4> Posted by 
            <% if review.first.user_id == nil %>
              Guest
            <% else %>
              <%= User.find(review.first.user_id).name %>
            <% end %>
              on <%= review[1].utc.getlocal.strftime('%b %d, %Y at %l:%M %P') %>
          </h4>
          <h4>Rating: <%= review.first.rating %></h4>
            <p><%= review.first.description %><p>
            <% if review.first.user_id == session[:user_id] && current_user %>
              <%= button_to "Edit review", edit_review_path(review.first), method: :get %>
              <%= button_to "Delete review", review_path(review.first), method: :delete %>
            <% end %>
          <hr>
          </li>
          <%= link_to "See all reviews", product_reviews_path(params[:id]) %> 
        <% end %> 
        <!-- ends iteration through reviews -->
      <% end %> 
      <!-- ends condition for whether there are any reviews -->
    </ul>
    <!-- ends reviews -->

    <% unless session[:user_id] == nil %> 
      <!-- start what owner of product can see -->
      <% if @product.user_id == current_user.id %> 
        <%= button_to "Edit this product", edit_product_path(@product.id), method: :get %><br>
        <%= link_to "View all your products", user_path(current_user.id) %>
      <% end %> 
      <!-- ends what merchant can see --> 
    <% end %> 
      
</div>

<hr>
<!-- I want to use this to get the users name! @users.where(id = @product.user_id).first.name -->
<div class="see_all_products_by_merchant">
  <%= link_to "View all products by #{@users.find_by(id: @product.user_id).name}", user_path(@product.user_id)  %>
</div>
<br>
<div class="go_back">
  <%= link_to "Back to browsing", root_path %>
</div>